### ISSUE TITLE
fmuResourceLocation

### ISSUE THREAD

**Issue by y-schneidereit** [CATIA-Systems/FMU-Standalone-App#1]
Hello,
i would like to execute your code with an own fmu exported by simulink.
The problem is, that my simulink fmu do not have an resources folder, so i do not know which path i should hand over to fmi2Instantiate(...). I try, as you do, to hand over a nullptr but that do not work.
Do you have any idea what i could do?

Thank you!

**Comment by t-sommer** [comment]
The application passes an empty string as `fmuResourceLocation` to `fmi2Instantiate()` (not `NULL`). Can you share an example to reproduce the problem?

**Comment by y-schneidereit** [comment]
I created a repository ([risingedge](https://github.com/y-schneidereit/risingedge)). Maybe you have an idea, why it does not work.

**Comment by t-sommer** [comment]
You have to include the FMI header before you call the FMI functions:

```C
#define FMI2_FUNCTION_PREFIX RisingEdge_

#include "fmi2Functions.h"

// ...

fmi2Component c = RisingEdge_fmi2Instantiate("instance1", fmi2CoSimulation, GUID, RESOURCE_LOCATION, &callbacks, fmi2False, fmi2False);

```
