### ISSUE TITLE
Nested FMU access violation

### ISSUE THREAD

**Issue by y-schneidereit** [CATIA-Systems/FMU-Standalone-App#2]
Hi,
unfortunately I have an access violation again at executing a nested FMU.
The error is: _Unable to load dynamic libary 'C:\...\*.dll'. Load Library Error: '126'_  It is the *.dll of the nested FMU.
Do you have an idea which include I forget?
Link to the project: [StandaloneNestedFMU](https://github.com/y-schneidereit/StandaloneNestedFMU_Addition)

Thank you for your help!

**Comment by t-sommer** [comment]
Can you double check that the `fmuResourceLocation` is a valid URI pointing to the `resources` folder with the extracted nested FMUs?

**Comment by y-schneidereit** [comment]
That solved the issue. 
The ``` fmuResourceLocation ``` had still pointing to the unziped FMU, as it is described in the [FMI specifications](https://fmi-standard.org/downloads/).
That the ```fmuResourceLocation``` at nested FMU has to pointing to the extracted nested ```resources``` folder should absolutely added to the [FMI specifications](https://fmi-standard.org/downloads/).
Thank you very much!
