### ISSUE TITLE
Nested FMU access violation: solver needed?

### ISSUE THREAD

**Issue by y-schneidereit** [CATIA-Systems/FMU-Standalone-App#3]
Hello,
I have another access violation, which I do not know how to fix. This time it is a nesded FMU of an Altair model. I guess the access violation is because the model has no access to the solver of the Altair model.
The nested FMU do not have source code. This also could be the problem.
You have an idea how to fix?
Link to the repository: https://github.com/y-schneidereit/StandaloneNestedFMU_PickAndPlace

Thank you for your help!

**Comment by t-sommer** [comment]
What is the motivation to use a source code FMU? Can't you just use the binary?

**Comment by y-schneidereit** [comment]
I would like to execute the FMU in a C Program. I think this is only possible with a source code FMU.

**Comment by t-sommer** [comment]
Unless you have a reason to use source code (e.g. to build for an embedded target) you should use the platform binary that comes with the FMU. Here's an example: https://github.com/modelica/Reference-FMUs/blob/master/examples/simulate_fmi2_cs.c.

**Comment by y-schneidereit** [comment]
I do not unterstand how you link the ```*.dll``` of the FMU.
Here (https://github.com/y-schneidereit/StandaloneFMU_PickAndPlace) I tried static link but it do not work.

**Comment by t-sommer** [comment]
> I do not unterstand how you link the *.dll of the FMU.

You load the symbols from the DLL dynamically. See the example I linked above to see how to do it.

**Comment by y-schneidereit** [comment]
I am sorry for the annoying questions, but I do not get the solution. Maybe you could have a look on my Repo I linked above.
When you do not have time for that I could understand.
